# Generated by Django 4.0.4 on 2022-05-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_threadmodel_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmodel',
            name='image',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
