# Generated by Django 4.0.4 on 2022-05-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_commentsmodel_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsmodel',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likesmodel',
            old_name='author',
            new_name='user',
        ),
    ]
